ARG from
FROM $from

COPY etc/ /etc/

RUN dnf -y install \
    @gnome-desktop \
    gnome-shell \
    gnome-shell-extension-nekotorch \
    gnome-software-rpm-ostree \
    default-flatpaks \
    --exclude gnome-boxes \
    --exclude gnome-connections \
    --exclude gnome-text-editor \
    --exclude yelp \
    --exclude baobab \
    --exclude evince \
    --exclude evince-djvu \
    --exclude gnome-calculator \
    --exclude gnome-calendar \
    --exclude gnome-characters \
    --exclude gnome-classic-session \
    --exclude gnome-clocks \
    --exclude gnome-contacts \
    --exclude gnome-font-viewer \
    --exclude gnome-logs \
    --exclude gnome-maps \
    --exclude gnome-system-monitor \
    --exclude gnome-user-docs \
    --exclude gnome-weather \
    --exclude totem \
    --exclude loupe \
    --exclude simple-scan \
    --exclude snapshot \
    --exclude gnome-tour \
    --exclude malcontent-control

RUN systemctl enable gdm.service

# clenup
RUN rm -rf /var/log/* && dnf clean all

RUN bootc container lint